# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import playerManagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('playerManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLog',
            fields=[
                ('player_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(null=True, upload_to=playerManagement.models.upload_to_player_dir)),
                ('uploaded_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
