# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:46
from __future__ import unicode_literals

import customLibrary.views_lib
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenManagement', '0021_screenanalytics'),
        ('playerManagement', '0002_playerlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAnalytics',
            fields=[
                ('player_analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_item_id', models.IntegerField(null=True)),
                ('content_id', models.IntegerField(null=True)),
                ('date', models.DateField(default=customLibrary.views_lib.today_date)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenManagement.Screen')),
            ],
        ),
    ]
