# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playerManagement', '0003_playeranalytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeranalytics',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
