# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerManagement', '0004_playeranalytics_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerAnalytics',
            new_name='MediaAnalytics',
        ),
    ]
