# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playerManagement', '0005_auto_20160820_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaanalytics',
            name='screen',
        ),
        migrations.DeleteModel(
            name='MediaAnalytics',
        ),
    ]
