# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 08:58
from __future__ import unicode_literals

import customLibrary.views_lib
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('screenManagement', '0021_screenanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAnalytics',
            fields=[
                ('player_analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('playlist_item_id', models.IntegerField(null=True)),
                ('content_id', models.IntegerField(null=True)),
                ('date', models.DateField(default=customLibrary.views_lib.today_date)),
                ('count', models.IntegerField(default=0)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenManagement.Screen')),
            ],
        ),
        migrations.CreateModel(
            name='ScreenAnalytics',
            fields=[
                ('screen_analytics_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_start_time', models.DateTimeField()),
                ('session_end_time', models.DateTimeField()),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='screenManagement.Screen')),
            ],
        ),
    ]
