# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlistManagement', '0005_auto_20160610_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='user_visible',
            field=models.BooleanField(default=True),
        ),
    ]
