# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('screenManagement', '0022_auto_20160806_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcmDevice',
            fields=[
                ('dev_id', models.CharField(max_length=50, unique=True, verbose_name=b'Device ID')),
                ('reg_id', models.CharField(max_length=255, unique=True, verbose_name=b'Registration ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Name')),
                ('is_active', models.BooleanField(default=False, verbose_name=b'Is active?')),
                ('fcm_device_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
            },
        ),
        migrations.AddField(
            model_name='screen',
            name='fcm_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='screenManagement.FcmDevice'),
        ),
    ]
