# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20160808_0700'),
        ('contentManagement', '0011_auto_20160703_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('widget_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Organization')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contentManagement.ContentType')),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
    ]
