# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 13:09
from __future__ import unicode_literals

import contentManagement.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contentManagement', '0012_auto_20160809_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='type',
        ),
        migrations.AddField(
            model_name='content',
            name='widget_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=contentManagement.models.upload_to_dir),
        ),
        migrations.AlterField(
            model_name='content',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contentManagement.Content'),
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
