# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-11 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scheduleManagement', '0015_auto_20160802_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('content_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('schedule_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_time', models.IntegerField(default=10)),
                ('position_index', models.IntegerField()),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduleitem_content_item_id', to='scheduleManagement.ContentItem')),
            ],
        ),
        migrations.AlterField(
            model_name='schedulepane',
            name='playlists',
            field=models.ManyToManyField(through='scheduleManagement.ScheduleItem', to='scheduleManagement.ContentItem'),
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='schedule_pane',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduleManagement.SchedulePane'),
        ),
    ]
